// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/skills": {
    params: {};
  };
  "/contacts": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:projectPath": {
    params: {
      "projectPath": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/skills" | "/contacts" | "/projects" | "/projects/:projectPath";
  };
  "routes/main-layout.tsx": {
    id: "routes/main-layout";
    page: "/" | "/skills" | "/contacts" | "/projects" | "/projects/:projectPath";
  };
  "routes/home-page.tsx": {
    id: "routes/home-page";
    page: "/";
  };
  "routes/skills-page.tsx": {
    id: "routes/skills-page";
    page: "/skills";
  };
  "routes/contacts-page.tsx": {
    id: "routes/contacts-page";
    page: "/contacts";
  };
  "routes/projects-list-page.tsx": {
    id: "routes/projects-list-page";
    page: "/projects";
  };
  "routes/project-details-page.tsx": {
    id: "routes/project-details-page";
    page: "/projects/:projectPath";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/main-layout": typeof import("./app/routes/main-layout.tsx");
  "routes/home-page": typeof import("./app/routes/home-page.tsx");
  "routes/skills-page": typeof import("./app/routes/skills-page.tsx");
  "routes/contacts-page": typeof import("./app/routes/contacts-page.tsx");
  "routes/projects-list-page": typeof import("./app/routes/projects-list-page.tsx");
  "routes/project-details-page": typeof import("./app/routes/project-details-page.tsx");
};